/**
 * Единый словарь пользовательских надписей (UI).
 * Используйте только LABELS и производные константы из этого файла.
 */
export const LABELS = {
  BRAND_NAME: 'Lingua-Bloom',
  BRAND_LOGO_ALT: 'Lingua-Bloom',

  CHAT_WITH_AI: 'Чат с AI',
  FROM_FILE: 'Из файла',
  NAV_CABINET: 'Кабинет',
  HISTORY: 'История',
  PROGRESS: 'Прогресс',
  SIGN_OUT: 'Выход',
  MOBILE_MENU: 'Меню',

  HOME_NAV_LOGIN: 'Войти',
  HOME_NAV_SIGN_UP: 'Регистрация',
  HOME_HERO_LINE_BEFORE: 'Пусть ваши возможности',
  HOME_HERO_HIGHLIGHT: 'расцветают',
  HOME_HERO_LINE_AFTER: 'с нашими AI-решениями',
  HOME_HERO_LEAD:
    'Lingua-Bloom превращает идеи и учебные материалы в интерактивные тесты за минуты: чат с ассистентом, загрузка PDF и изображений, автоматическая проверка и мотивирующая обратная связь.',
  HOME_CTA_START: 'Начать обучение',
  HOME_CTA_HAS_ACCOUNT: 'Уже есть аккаунт',
  HOME_FEATURES_TITLE: 'Ключевые возможности',
  HOME_FEATURE_CHAT_TITLE: 'ИИ-чат для создания тестов',
  HOME_FEATURE_CHAT_TEXT:
    'Опишите идею теста — ассистент уточнит детали и подготовит интерактивную страницу с заданиями.',
  HOME_FEATURE_UPLOAD_TITLE: 'PDF и изображения',
  HOME_FEATURE_UPLOAD_TEXT:
    'Загрузите материал: платформа извлечёт содержание и соберёт тест с упражнениями и проверкой.',
  HOME_FEATURE_PAGE_TITLE: 'Коллекция учебных материалов',
  HOME_FEATURE_PAGE_TEXT: 'Создайте коллекцию учебных материалов и используйте их в своих уроках',
  HOME_FEATURE_FEEDBACK_TITLE: 'Обратная связь',
  HOME_FEATURE_FEEDBACK_TEXT: 'Мгновенная оценка ответов, пояснения к ошибкам и ощущение прогресса.',
  HOME_FOOTER: 'Made by Волкова Анна. 2026',

  META_TITLE_DEFAULT: 'Lingua-Bloom — интерактивные тесты с ИИ',
  META_TITLE_TEMPLATE: '%s | Lingua-Bloom',
  META_DESCRIPTION:
    'Платформа, где языковое обучение расцветает: тесты из идей, PDF и изображений за минуты. Персонализация, проверка заданий и мотивирующий интерфейс.',
  META_KEYWORD_1: 'Lingua-Bloom',
  META_KEYWORD_2: 'изучение языков',
  META_KEYWORD_3: 'ИИ тесты',
  META_KEYWORD_4: 'интерактивное обучение',
  META_KEYWORD_5: 'GigaChat',
  META_AUTHOR_NAME: 'Lingua-Bloom',
  META_OG_TITLE: 'Lingua-Bloom — интерактивные тесты с ИИ',
  META_OG_DESCRIPTION:
    'Пусть ваши возможности расцветают с нашими AI-решениями: тесты, упражнения и обратная связь.',
  META_TWITTER_TITLE: 'Lingua-Bloom — интерактивные тесты с ИИ',
  META_TWITTER_DESCRIPTION: 'Идеи и материалы превращаются в интерактивные тесты за минуты.',

  DASHBOARD_WELCOME_BACK: 'С возвращением, {name}!',
  DASHBOARD_SUBTITLE:
    'Создавайте интерактивные тесты из чата или файла — и возвращайтесь к прогрессу.',
  DASHBOARD_CARD_CHAT_DESC: 'Ассистент уточнит цели и сгенерирует страницу теста.',
  DASHBOARD_CARD_UPLOAD_TITLE: 'Из PDF или фото',
  DASHBOARD_CARD_UPLOAD_DESC: 'Загрузите материал — получите HTML-тест с заданиями.',
  DASHBOARD_CARD_PROGRESS_TITLE: 'Прогресс',
  DASHBOARD_CARD_PROGRESS_STATS: '{xp} XP · {count} тестов создано',
  DASHBOARD_STAT_LESSONS_TOTAL: 'тестов всего',
  DASHBOARD_STAT_TESTS_LEGACY: 'Тесты (legacy)',
  DASHBOARD_STAT_TEST_ATTEMPTS: 'Попытки тестов',
  DASHBOARD_STAT_AVG_SCORE: 'Средний балл',
  DASHBOARD_LESSONS_TITLE: 'Интерактивные тесты',
  DASHBOARD_LESSONS_DESC: 'HTML-страницы с заданиями',
  DASHBOARD_ALL_HISTORY: 'Вся история',
  DASHBOARD_LESSONS_EMPTY: 'Пока нет тестов — создайте первый.',
  DASHBOARD_LESSONS_CHAT_SHORT: 'Чат',
  DASHBOARD_LESSONS_FILE_SHORT: 'Файл',
  DASHBOARD_TESTS_RECENT_TITLE: 'Недавние результаты тестов',
  DASHBOARD_TESTS_RECENT_DESC: 'Классические PDF-тесты',
  DASHBOARD_TESTS_NO_ATTEMPTS: 'Пока нет попыток',
  DASHBOARD_TO_TESTS: 'К тестам',
  DASHBOARD_SCORE_CORRECT: '{score}/{total} верно',
  DASHBOARD_TESTS_LEGACY_SECTION: 'Тесты (legacy)',
  DEFAULT_STUDENT_NAME: 'ученик',
  TEST_FALLBACK_TITLE: 'Тест',

  CREATE_BACK_CABINET: '← Кабинет',
  CREATE_PAGE_TITLE: 'Чат с AI',
  CREATE_PAGE_DESCRIPTION:
    'Опишите идею теста — ассистент уточнит детали. Затем нажмите «Создать страницу теста»: GigaChat соберёт интерактивный HTML.',
  CREATE_ERROR_ASSISTANT: 'Ошибка ассистента',
  CREATE_ERROR_EMPTY: 'Пустой ответ',
  CREATE_ERROR_GENERIC: 'Ошибка',
  CREATE_ERROR_GENERATION: 'Ошибка генерации',
  CREATE_ERROR_NEED_MESSAGE: 'Сначала напишите хотя бы одно сообщение.',
  CREATE_HINT_EXAMPLE: 'Например: «тест по временам немецкого для A2, тема путешествия».',
  CREATE_ASSISTANT_TYPING: 'Ассистент пишет…',
  CREATE_PLACEHOLDER_MESSAGE: 'Ваше сообщение…',
  CREATE_SEND: 'Отправить',
  CREATE_GENERATE_LESSON_PAGE: 'Создать страницу теста',
  CREATE_LESSON_TITLE_LABEL: 'Название теста',
  CREATE_LESSON_TITLE_OPTIONAL: 'необязательно — иначе подставится из переписки',
  CREATE_LESSON_TITLE_PLACEHOLDER: 'Например: Present Simple, путешествия',
  CREATE_CORRECT_ANSWERS_LABEL: 'Правильные ответы',
  CREATE_CORRECT_ANSWERS_OPTIONAL:
    'необязательно — если пусто и в материале нет ключей, ИИ выберет ответы сам',
  CREATE_CORRECT_ANSWERS_PLACEHOLDER:
    'Например: 1 — B, 2 — goes, 3. правильный порядок: She often visits museums…',

  UPLOAD_ERROR_FILE_TYPE: 'Загрузите PDF или изображение (PNG, JPEG, WebP)',
  UPLOAD_ERROR_GENERATION: 'Ошибка генерации',
  UPLOAD_ERROR_GENERIC: 'Ошибка',
  UPLOAD_STEP_FILE: 'Файл',
  UPLOAD_STEP_TITLE: 'Название',
  UPLOAD_STEP_DONE: 'Готово',
  UPLOAD_CARD_MATERIAL_TITLE: 'Материал для теста',
  UPLOAD_CARD_MATERIAL_DESC: 'PDF или скан страницы — платформа создаст интерактивную HTML-страницу теста.',
  UPLOAD_DROP_RELEASE: 'Отпустите файл',
  UPLOAD_DROP_PROMPT: 'Перетащите PDF или изображение',
  UPLOAD_MAX_SIZE: 'до 12 МБ',
  UPLOAD_FILE_SIZE_MB: '{size} МБ',
  UPLOAD_NEXT: 'Далее',
  UPLOAD_LESSON_TITLE: 'Название теста',
  UPLOAD_LESSON_TITLE_DESC: 'ИИ использует файл и название при генерации страницы.',
  UPLOAD_LABEL_TITLE: 'Заголовок',
  UPLOAD_TITLE_PLACEHOLDER: 'Например: Путешествия — лексика',
  UPLOAD_CORRECT_ANSWERS_LABEL: 'Правильные ответы',
  UPLOAD_CORRECT_ANSWERS_OPTIONAL:
    'необязательно — если пусто и в файле нет ключей, ИИ выберет ответы сам',
  UPLOAD_CORRECT_ANSWERS_PLACEHOLDER:
    'Свободная форма: номера заданий, буквы вариантов, эталонные предложения…',
  UPLOAD_BACK: 'Назад',
  UPLOAD_CREATE_LESSON: 'Создать тест',
  UPLOAD_GENERATING_TITLE: 'Генерируем страницу теста',
  UPLOAD_GENERATING_DESC: 'GigaChat собирает интерактивный HTML. Это может занять до минуты.',
  LESSON_PARTIAL_VALIDATION_ALERT_TITLE: 'Часть заданий не попала в тест',
  LESSON_PARTIAL_VALIDATION_ALERT_INTRO:
    'Ниже перечислены элементы, которые не прошли проверку формата и были исключены. Остальные задания сохранены в тесте.',

  HISTORY_SUBTITLE: 'тесты, тесты и попытки',
  HISTORY_NEW_LESSON: 'Новый тест',
  HISTORY_FILE_BUTTON: 'Файл',
  HISTORY_TAB_LESSONS: 'тесты ({count})',
  HISTORY_TAB_TESTS: 'Тесты ({count})',
  HISTORY_TAB_ATTEMPTS: 'Попытки ({count})',
  HISTORY_LESSONS_EMPTY_TITLE: 'Пока нет тестов',
  HISTORY_LESSONS_EMPTY_DESC: 'Создайте интерактивную HTML-страницу из чата или файла.',
  HISTORY_CHAT_SHORT: 'Чат',
  HISTORY_UPLOAD_SHORT: 'Загрузка',
  HISTORY_TESTS_EMPTY_TITLE: 'Нет тестов',
  HISTORY_TESTS_EMPTY_DESC: 'Классические тесты из PDF (legacy).',
  HISTORY_CREATE_TEST: 'Создать тест',
  HISTORY_TEST_FILE_LABEL: 'Файл: {name}',
  HISTORY_QUESTION_COUNT: '{count} вопросов',
  HISTORY_ATTEMPTS_EMPTY_TITLE: 'Нет попыток',
  HISTORY_ATTEMPTS_EMPTY_DESC: 'Пройдите тест, чтобы увидеть результат здесь.',
  HISTORY_TO_TESTS: 'К тестам',
  HISTORY_ATTEMPT_SCORE: '{score}/{total} верно',
  HISTORY_DURATION_EM_DASH: '—',
  HISTORY_DURATION: '{mins}м {secs}с',

  PROGRESS_PAGE_TITLE: 'Прогресс и достижения',
  PROGRESS_PAGE_SUBTITLE: 'Отслеживайте рост: каждый новый тест добавляет XP.',
  PROGRESS_XP_BAR_CAPTION: 'Общий прогресс XP',
  PROGRESS_XP_BAR_FOOTNOTE: '{xp} XP · визуально до 200 XP = 100% полосы',
  PROGRESS_CARD_XP: 'XP',
  PROGRESS_CARD_LESSONS: 'тестов',
  PROGRESS_CARD_STREAK: 'Серия дней',
  PROGRESS_STREAK_NOTE: 'скоро: автоматический подсчёт',
  PROGRESS_ACHIEVEMENTS_TITLE: 'Достижения',
  PROGRESS_ACHIEVEMENTS_DESC: 'Разблокированные награды',
  PROGRESS_ACHIEVEMENTS_EMPTY: 'Пока нет записей — создайте первый тест!',
  PROGRESS_NEW_LESSON: 'Новый тест',

  LEARN_VIEW_TO_CABINET: 'В кабинет',
  LEARN_VIEW_NEW_TAB: 'Отдельная вкладка',

  SERVICE_CHECK_BACK: 'Назад',
  SERVICE_CHECK_TITLE: 'Проверка бэкенда',
  SERVICE_CHECK_DESCRIPTION:
    'Запрос к Next API /api/backend-health, который обращается к Express static-server (/health). Перед проверкой запустите pnpm serve:static.',
  SERVICE_CHECK_BUTTON: 'Проверить сервис',
  SERVICE_CHECK_LOADING: 'Проверяю…',
  SERVICE_CHECK_SUCCESS: 'Успех',
  SERVICE_CHECK_ERROR: 'Ошибка',

  DELETE_TEST_TITLE: 'Delete Test',
  DELETE_TEST_DESCRIPTION:
    'Are you sure you want to delete "{title}"? This will also delete all associated test attempts. This action cannot be undone.',
  DELETE_TEST_CANCEL: 'Cancel',
  DELETE_TEST_CONFIRM: 'Delete',
  DELETE_TEST_DELETING: 'Deleting...',

  AUTH_BRAND_DISPLAY: 'Lingua Bloom',
  AUTH_BRAND_LOGO_ALT: 'Lingua Bloom',
  AUTH_LOGIN_TAGLINE: 'Welcome back! Sign in to continue.',
  AUTH_SIGN_IN_TITLE: 'Sign In',
  AUTH_SIGN_IN_DESCRIPTION: 'Enter your email and password to access your account',
  AUTH_OR_EMAIL: 'or with email',
  AUTH_EMAIL_LABEL: 'Email',
  AUTH_EMAIL_PLACEHOLDER: 'you@example.com',
  AUTH_PASSWORD_LABEL: 'Password',
  AUTH_PASSWORD_PLACEHOLDER: 'Enter your password',
  AUTH_SIGNING_IN: 'Signing in...',
  AUTH_SIGN_IN_SUBMIT: 'Sign In',
  AUTH_NO_ACCOUNT: "Don't have an account?",
  AUTH_SIGN_UP_LINK: 'Sign up',

  AUTH_SIGNUP_TAGLINE: 'Create your account to get started.',
  AUTH_SIGNUP_TITLE: 'Create Account',
  AUTH_SIGNUP_DESCRIPTION: 'Enter your details to create a new account',
  AUTH_GOOGLE_SIGN_UP: 'Sign up with Google',
  AUTH_GOOGLE_CONTINUE: 'Continue with Google',
  AUTH_DISPLAY_NAME_LABEL: 'Display Name',
  AUTH_DISPLAY_NAME_PLACEHOLDER: 'Your name',
  AUTH_PASSWORD_CREATE_PLACEHOLDER: 'Create a password (min. 6 characters)',
  AUTH_CONFIRM_PASSWORD_LABEL: 'Confirm Password',
  AUTH_CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm your password',
  AUTH_CREATING_ACCOUNT: 'Creating account...',
  AUTH_CREATE_ACCOUNT_SUBMIT: 'Create Account',
  AUTH_HAVE_ACCOUNT: 'Already have an account?',
  AUTH_SIGN_IN_LINK: 'Sign in',
  AUTH_PASSWORD_MISMATCH: 'Passwords do not match',
  AUTH_PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters',

  AUTH_EMAIL_CHECK_TITLE: 'Check Your Email',
  AUTH_EMAIL_CHECK_BEFORE: "We've sent a confirmation link to ",
  AUTH_EMAIL_CHECK_AFTER: '. Please check your inbox and click the link to activate your account.',
  AUTH_BACK_TO_SIGN_IN: 'Back to Sign In',

  OAUTH_CONSENT_TITLE: 'Authorize application',
  OAUTH_CONSENT_LEAD:
    'A third-party app is requesting access to your Lingua Bloom account. Review the details before you continue.',
  OAUTH_CONSENT_CLIENT_LABEL: 'Application',
  OAUTH_CONSENT_REDIRECT_LABEL: 'Redirect URI',
  OAUTH_CONSENT_SCOPES_LABEL: 'Requested permissions',
  OAUTH_CONSENT_ACCOUNT_LABEL: 'Signed in as',
  OAUTH_CONSENT_APPROVE: 'Allow access',
  OAUTH_CONSENT_DENY: 'Deny',
  OAUTH_CONSENT_MISSING_ID: 'Invalid link: authorization request is missing.',
  OAUTH_CONSENT_LOAD_ERROR: 'Could not load this authorization request. It may have expired.',

  AUTH_SIGNUP_SUCCESS_LOGO_ALT: 'Lingua Bloom Logo',
  AUTH_SIGNUP_SUCCESS_TITLE: 'Check Your Email',
  AUTH_SIGNUP_SUCCESS_DESC: "We've sent you a confirmation link to verify your email address.",
  AUTH_SIGNUP_SUCCESS_HINT_1: 'Click the link in the email to activate your account and start creating tests.',
  AUTH_SIGNUP_SUCCESS_HINT_2: "Don't see the email? Check your spam folder.",

  AUTH_ERROR_TITLE: 'Sorry, something went wrong.',
  AUTH_ERROR_CODE_PREFIX: 'Code error: ',
  AUTH_ERROR_UNSPECIFIED: 'An unspecified error occurred.',

  TEST_BRAND_DISPLAY: 'Lingua Bloom',
  TEST_BRAND_LOGO_ALT: 'Lingua Bloom',
  TEST_BACK_UPLOAD: 'Back to upload',
  TEST_BASED_ON: 'Based on: {name}',
  TEST_QUESTIONS_LABEL: 'Questions',
  TEST_DIFFICULTY_LABEL: 'Difficulty',
  TEST_DIFFICULTY_MEDIUM: 'Medium',
  TEST_QUESTION_TYPES: 'Question Types:',
  TEST_START: 'Start Test',
  TEST_COMPLETE_TITLE: 'Test Complete!',
  TEST_RESULTS_SCORE_LINE: 'You got {correct} out of {total} questions correct',
  TEST_TIME_PREFIX: 'Time: ',
  TEST_RETAKE: 'Retake Test',
  TEST_NEW_UPLOAD: 'New upload',
  TEST_REVIEW_TITLE: 'Question Review',
  TEST_REVIEW_DESC: 'Review your answers and learn from mistakes',
  TEST_QUESTION_NUMBER: 'Question {n}',
  TEST_YOUR_ANSWER: 'Your answer: ',
  TEST_NO_ANSWER: 'No answer',
  TEST_CORRECT_ANSWER: 'Correct answer: ',
  TEST_EXPLANATION: 'Explanation:',
  TEST_QUESTION_INDEX: 'Question {n}',
  TEST_YOUR_ANSWER_LABEL: 'Your Answer',
  TEST_ANSWER_PLACEHOLDER: 'Type your answer here...',
  TEST_PREVIOUS: 'Previous',
  TEST_SUBMITTING: 'Submitting...',
  TEST_SUBMIT: 'Submit Test',
  TEST_NEXT: 'Next',
  TEST_NAVIGATOR: 'Question Navigator',

  DRAFT_LOADING: 'Loading…',
  DRAFT_REDIRECTING: 'Redirecting…',

  LEARN_DOC_AUTH_REQUIRED: 'Требуется вход',
  LEARN_DOC_NOT_FOUND: 'тест не найден',

  DEFAULT_LESSON_TITLE: 'тест',
  DEFAULT_LESSON_TITLE_FROM_CHAT: 'тест из чата',
  API_GENERATE_NO_FILE: 'Файл не передан',
  API_GENERATE_PDF_EXTRACT_FAILED: 'Не удалось извлечь текст из PDF',
  API_GENERATE_UNSUPPORTED_FILE: 'Поддерживаются PDF и изображения',
} as const

export type HomeFeatureKey = 'chat' | 'upload' | 'page' | 'feedback'

export const HOME_FEATURES: readonly { key: HomeFeatureKey; title: string; text: string }[] = [
  { key: 'chat', title: LABELS.HOME_FEATURE_CHAT_TITLE, text: LABELS.HOME_FEATURE_CHAT_TEXT },
  { key: 'upload', title: LABELS.HOME_FEATURE_UPLOAD_TITLE, text: LABELS.HOME_FEATURE_UPLOAD_TEXT },
  { key: 'page', title: LABELS.HOME_FEATURE_PAGE_TITLE, text: LABELS.HOME_FEATURE_PAGE_TEXT },
  { key: 'feedback', title: LABELS.HOME_FEATURE_FEEDBACK_TITLE, text: LABELS.HOME_FEATURE_FEEDBACK_TEXT },
]
