/**
 * Единый словарь пользовательских надписей (UI).
 * Используйте только LABELS и производные константы из этого файла.
 */
export const LABELS = {
  BRAND_NAME: 'Lingua-Bloom',
  BRAND_LOGO_ALT: 'Lingua-Bloom',

  CHAT_WITH_AI: 'Чат с ИИ',
  NAV_DASHBOARD: 'Главная',
  NAV_FROM_PDF: 'Из PDF или фото',
  NAV_HISTORY_TESTS: 'История тестов',
  /** Кнопка открытия навигации на узком экране */
  NAV_MENU: 'Меню',
  SIGN_OUT: 'Выход',

  HOME_NAV_LOGIN: 'Войти',
  HOME_NAV_SIGN_UP: 'Регистрация',
  HOME_HERO_LINE_BEFORE: 'Пусть ваши возможности',
  HOME_HERO_HIGHLIGHT: 'расцветают',
  HOME_HERO_LINE_AFTER: 'с нашими AI-решениями',
  HOME_HERO_LEAD:
    'Lingua-Bloom превращает идеи и учебные материалы в интерактивные тесты за минуты: чат с ассистентом, загрузка PDF и изображений, автоматическая проверка и мотивирующая обратная связь.',
  HOME_CTA_START: 'Начать обучение',
  HOME_CTA_HAS_ACCOUNT: 'Уже есть аккаунт',
  HOME_FOOTER: 'Made by Волкова Анна. 2026',

  META_TITLE_DEFAULT: 'Lingua-Bloom — интерактивные тесты с ИИ',
  META_TITLE_TEMPLATE: '%s | Lingua-Bloom',
  META_DESCRIPTION:
    'Платформа, где языковое обучение расцветает: тесты из идей, PDF и изображений за минуты. Персонализация, проверка заданий и мотивирующий интерфейс.',
  META_KEYWORD_1: 'Lingua-Bloom',
  META_KEYWORD_2: 'изучение языков',
  META_KEYWORD_3: 'ИИ тесты',
  META_KEYWORD_4: 'интерактивное обучение',
  META_KEYWORD_5: 'GigaChat',
  META_AUTHOR_NAME: 'Lingua-Bloom',
  META_OG_TITLE: 'Lingua-Bloom — интерактивные тесты с ИИ',
  META_OG_DESCRIPTION:
    'Пусть ваши возможности расцветают с нашими AI-решениями: тесты, упражнения и обратная связь.',
  META_TWITTER_TITLE: 'Lingua-Bloom — интерактивные тесты с ИИ',
  META_TWITTER_DESCRIPTION: 'Идеи и материалы превращаются в интерактивные тесты за минуты.',

  DASHBOARD_WELCOME_BACK: 'С возвращением, {name}!',
  DASHBOARD_SUBTITLE: 'Создавайте тесты в чате с ИИ или из PDF и фото — недавние тесты ниже.',
  DASHBOARD_CARD_CHAT_DESC: 'Опишите идею и сгенерируйте интерактивный тест.',
  DASHBOARD_CARD_UPLOAD_TITLE: 'Из PDF или фото',
  DASHBOARD_CARD_UPLOAD_DESC: 'Загрузите материал — получите HTML-тест с заданиями.',
  DASHBOARD_CARD_HISTORY_TITLE: 'История тестов',
  DASHBOARD_CARD_HISTORY_DESC: 'Все созданные тесты в одном списке.',
  DASHBOARD_LESSONS_TITLE: 'Недавние тесты',
  DASHBOARD_LESSONS_DESC: 'Откройте тест для просмотра и правок с ИИ.',
  DASHBOARD_ALL_HISTORY: 'Вся история',
  DASHBOARD_LESSONS_EMPTY: 'Пока нет тестов — создайте первый.',
  DASHBOARD_LESSONS_CHAT_SHORT: 'Чат с ИИ',
  DASHBOARD_LESSONS_FILE_SHORT: 'Из PDF или фото',
  DEFAULT_STUDENT_NAME: 'ученик',
  TEST_FALLBACK_TITLE: 'Тест',

  CREATE_BACK_CABINET: '← Главная',
  CREATE_ERROR_ASSISTANT: 'Ошибка ассистента',
  CREATE_ERROR_EMPTY: 'Пустой ответ',
  CREATE_ERROR_GENERIC: 'Ошибка',
  CREATE_ERROR_GENERATION: 'Ошибка генерации',
  CREATE_ERROR_NEED_MESSAGE: 'Сначала напишите хотя бы одно сообщение.',
  CREATE_HINT_EXAMPLE: 'Например: «тест по временам немецкого для A2, тема путешествия».',
  CREATE_ASSISTANT_TYPING: 'Ассистент пишет…',
  CREATE_PLACEHOLDER_MESSAGE: 'Ваше сообщение…',
  CREATE_SEND: 'Отправить',
  CREATE_GENERATE_TEST: 'Сгенерировать тест',
  CREATE_OPTIONAL_FORM_CAPTION: 'Дополнительно (можно пропустить)',
  CREATE_FORM_SUBJECT: 'Предмет',
  CREATE_FORM_SUBJECT_PH: 'Например: немецкий язык, A2',
  CREATE_FORM_TASK_COUNT: 'Количество заданий',
  CREATE_FORM_LEVEL: 'Уровень студентов',
  CREATE_FORM_LEVEL_PH: 'Выберите уровень',
  CREATE_FORM_TASK_TYPES: 'Типы заданий',
  CREATE_ANSWERS_DIALOG_TITLE: 'Правильные ответы',
  CREATE_ANSWERS_DIALOG_DESC:
    'Есть ли у вас правильные ответы для теста? (Необязательно) Если да — опишите их здесь; можно оставить пустым.',
  CREATE_ANSWERS_DIALOG_PLACEHOLDER:
    'Например: задание 1 — B, задание 2 — порядок слов: She goes to school…',
  CREATE_ANSWERS_DIALOG_CANCEL: 'Отмена',
  CREATE_ANSWERS_DIALOG_CONFIRM: 'Сгенерировать тест',

  UPLOAD_ERROR_FILE_TYPE: 'Загрузите PDF или изображение (PNG, JPEG, WebP)',
  UPLOAD_ERROR_GENERATION: 'Ошибка генерации',
  UPLOAD_ERROR_GENERIC: 'Ошибка',
  UPLOAD_STEP_FILE: 'Файл',
  UPLOAD_STEP_TITLE: 'Название',
  UPLOAD_STEP_DONE: 'Готово',
  UPLOAD_CARD_MATERIAL_TITLE: 'Материал для теста',
  UPLOAD_CARD_MATERIAL_DESC: 'PDF или скан страницы — платформа создаст интерактивную HTML-страницу теста.',
  UPLOAD_DROP_RELEASE: 'Отпустите файл',
  UPLOAD_DROP_PROMPT: 'Перетащите PDF или изображение',
  UPLOAD_MAX_SIZE: 'до 12 МБ',
  UPLOAD_FILE_SIZE_MB: '{size} МБ',
  UPLOAD_NEXT: 'Далее',
  UPLOAD_LESSON_TITLE: 'Название теста',
  UPLOAD_LESSON_TITLE_DESC: 'ИИ использует файл и название при генерации страницы.',
  UPLOAD_LABEL_TITLE: 'Заголовок',
  UPLOAD_TITLE_PLACEHOLDER: 'Например: Путешествия — лексика',
  UPLOAD_CORRECT_ANSWERS_LABEL: 'Правильные ответы',
  UPLOAD_CORRECT_ANSWERS_OPTIONAL:
    'необязательно — если пусто и в файле нет ключей, ИИ выберет ответы сам',
  UPLOAD_CORRECT_ANSWERS_PLACEHOLDER:
    'Свободная форма: номера заданий, буквы вариантов, эталонные предложения…',
  UPLOAD_BACK: 'Назад',
  UPLOAD_CREATE_LESSON: 'Создать тест',
  UPLOAD_GENERATING_TITLE: 'Генерируем страницу теста',
  UPLOAD_GENERATING_DESC: 'GigaChat собирает интерактивный HTML. Это может занять до минуты.',
  LESSON_PARTIAL_VALIDATION_ALERT_TITLE: 'Часть заданий не попала в тест',
  LESSON_PARTIAL_VALIDATION_ALERT_INTRO:
    'Ниже перечислены элементы, которые не прошли проверку формата и были исключены. Остальные задания сохранены в тесте.',

  HISTORY_SUBTITLE: 'Созданные интерактивные тесты',
  HISTORY_NEW_LESSON: 'Новый тест',
  HISTORY_FILE_BUTTON: 'Из PDF или фото',
  HISTORY_LESSONS_EMPTY_TITLE: 'Пока нет тестов',
  HISTORY_LESSONS_EMPTY_DESC: 'Создайте интерактивную HTML-страницу из чата или файла.',
  HISTORY_CHAT_SHORT: 'Чат с ИИ',
  HISTORY_UPLOAD_SHORT: 'Из PDF или фото',
  HISTORY_BACK_DASHBOARD: '← Главная',
  LEARN_VIEW_TO_CABINET: 'На главную',
  LEARN_VIEW_NEW_TAB: 'Отдельная вкладка',
  LEARN_EDIT_WITH_AI: 'Редактировать с помощью ИИ',
  LEARN_EDIT_INSTRUCTION_LABEL: 'Что изменить в тесте?',
  LEARN_EDIT_INSTRUCTION_PLACEHOLDER:
    'Например: сделай вопросы короче; исправь опечатку в вопросе 3; добавь вариант D к вопросу 5.',
  LEARN_EDIT_SUBMIT: 'Применить',
  LEARN_EDIT_CANCEL: 'Отмена',
  LEARN_EDIT_ERROR_GENERIC: 'Не удалось применить правки',

  AUTH_BRAND_DISPLAY: 'Lingua Bloom',
  AUTH_BRAND_LOGO_ALT: 'Lingua Bloom',
  AUTH_LOGIN_TAGLINE: 'Welcome back! Sign in to continue.',
  AUTH_SIGN_IN_TITLE: 'Sign In',
  AUTH_SIGN_IN_DESCRIPTION: 'Enter your email and password to access your account',
  AUTH_OR_EMAIL: 'or with email',
  AUTH_EMAIL_LABEL: 'Email',
  AUTH_EMAIL_PLACEHOLDER: 'you@example.com',
  AUTH_PASSWORD_LABEL: 'Password',
  AUTH_PASSWORD_PLACEHOLDER: 'Enter your password',
  AUTH_SIGNING_IN: 'Signing in...',
  AUTH_SIGN_IN_SUBMIT: 'Sign In',
  AUTH_NO_ACCOUNT: "Don't have an account?",
  AUTH_SIGN_UP_LINK: 'Sign up',

  AUTH_SIGNUP_TAGLINE: 'Create your account to get started.',
  AUTH_SIGNUP_TITLE: 'Create Account',
  AUTH_SIGNUP_DESCRIPTION: 'Enter your details to create a new account',
  AUTH_GOOGLE_SIGN_UP: 'Sign up with Google',
  AUTH_GOOGLE_CONTINUE: 'Continue with Google',
  AUTH_DISPLAY_NAME_LABEL: 'Display Name',
  AUTH_DISPLAY_NAME_PLACEHOLDER: 'Your name',
  AUTH_PASSWORD_CREATE_PLACEHOLDER: 'Create a password (min. 6 characters)',
  AUTH_CONFIRM_PASSWORD_LABEL: 'Confirm Password',
  AUTH_CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm your password',
  AUTH_CREATING_ACCOUNT: 'Creating account...',
  AUTH_CREATE_ACCOUNT_SUBMIT: 'Create Account',
  AUTH_HAVE_ACCOUNT: 'Already have an account?',
  AUTH_SIGN_IN_LINK: 'Sign in',
  AUTH_PASSWORD_MISMATCH: 'Passwords do not match',
  AUTH_PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters',

  AUTH_EMAIL_CHECK_TITLE: 'Check Your Email',
  AUTH_EMAIL_CHECK_BEFORE: "We've sent a confirmation link to ",
  AUTH_EMAIL_CHECK_AFTER: '. Please check your inbox and click the link to activate your account.',
  AUTH_BACK_TO_SIGN_IN: 'Back to Sign In',

  OAUTH_CONSENT_TITLE: 'Authorize application',
  OAUTH_CONSENT_LEAD:
    'A third-party app is requesting access to your Lingua Bloom account. Review the details before you continue.',
  OAUTH_CONSENT_CLIENT_LABEL: 'Application',
  OAUTH_CONSENT_REDIRECT_LABEL: 'Redirect URI',
  OAUTH_CONSENT_SCOPES_LABEL: 'Requested permissions',
  OAUTH_CONSENT_ACCOUNT_LABEL: 'Signed in as',
  OAUTH_CONSENT_APPROVE: 'Allow access',
  OAUTH_CONSENT_DENY: 'Deny',
  OAUTH_CONSENT_MISSING_ID: 'Invalid link: authorization request is missing.',
  OAUTH_CONSENT_LOAD_ERROR: 'Could not load this authorization request. It may have expired.',

  AUTH_SIGNUP_SUCCESS_LOGO_ALT: 'Lingua Bloom Logo',
  AUTH_SIGNUP_SUCCESS_TITLE: 'Check Your Email',
  AUTH_SIGNUP_SUCCESS_DESC: "We've sent you a confirmation link to verify your email address.",
  AUTH_SIGNUP_SUCCESS_HINT_1: 'Click the link in the email to activate your account and start creating tests.',
  AUTH_SIGNUP_SUCCESS_HINT_2: "Don't see the email? Check your spam folder.",

  AUTH_ERROR_TITLE: 'Sorry, something went wrong.',
  AUTH_ERROR_CODE_PREFIX: 'Code error: ',
  AUTH_ERROR_UNSPECIFIED: 'An unspecified error occurred.',

  TEST_BRAND_DISPLAY: 'Lingua Bloom',
  TEST_BRAND_LOGO_ALT: 'Lingua Bloom',
  TEST_BACK_UPLOAD: 'Back to upload',
  TEST_BASED_ON: 'Based on: {name}',
  TEST_QUESTIONS_LABEL: 'Questions',
  TEST_DIFFICULTY_LABEL: 'Difficulty',
  TEST_DIFFICULTY_MEDIUM: 'Medium',
  TEST_QUESTION_TYPES: 'Question Types:',
  TEST_START: 'Start Test',
  TEST_COMPLETE_TITLE: 'Test Complete!',
  TEST_RESULTS_SCORE_LINE: 'You got {correct} out of {total} questions correct',
  TEST_TIME_PREFIX: 'Time: ',
  TEST_RETAKE: 'Retake Test',
  TEST_NEW_UPLOAD: 'New upload',
  TEST_REVIEW_TITLE: 'Question Review',
  TEST_REVIEW_DESC: 'Review your answers and learn from mistakes',
  TEST_QUESTION_NUMBER: 'Question {n}',
  TEST_YOUR_ANSWER: 'Your answer: ',
  TEST_NO_ANSWER: 'No answer',
  TEST_CORRECT_ANSWER: 'Correct answer: ',
  TEST_EXPLANATION: 'Explanation:',
  TEST_QUESTION_INDEX: 'Question {n}',
  TEST_YOUR_ANSWER_LABEL: 'Your Answer',
  TEST_ANSWER_PLACEHOLDER: 'Type your answer here...',
  TEST_PREVIOUS: 'Previous',
  TEST_SUBMITTING: 'Submitting...',
  TEST_SUBMIT: 'Submit Test',
  TEST_NEXT: 'Next',
  TEST_NAVIGATOR: 'Question Navigator',

  DRAFT_LOADING: 'Loading…',
  DRAFT_REDIRECTING: 'Redirecting…',

  LEARN_DOC_AUTH_REQUIRED: 'Требуется вход',
  LEARN_DOC_NOT_FOUND: 'тест не найден',

  DEFAULT_LESSON_TITLE: 'тест',
  DEFAULT_LESSON_TITLE_FROM_CHAT: 'тест из чата',
  API_GENERATE_NO_FILE: 'Файл не передан',
  API_GENERATE_PDF_EXTRACT_FAILED: 'Не удалось извлечь текст из PDF',
  API_GENERATE_UNSUPPORTED_FILE: 'Поддерживаются PDF и изображения',
} as const
